name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "luajit-2.1.0-beta3"

    - name: Install luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install teal
      run: luarocks install tl

    - name: Build crates.nvim
      run: tl build
    
    - name: Generate docs
      run: ./scripts/gen_doc.lua

    - name: Check git status
      run: if [[ $(git status --short lua) != "" ]]; then exit 1; fi

